config/routes.rb
Rails.application.routes.draw do
  resources :sub_tasks
  resources :tasks do
    get 'tasks/sub_task/:id', to: 'sub_tasks#index'
    get 'tasks/sub_task/new', to: 'sub_tasks#new'
  end
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/sub_task.rb
class SubTask < ActiveRecord::Base
  belongs_to :task
  belongs_to :user
  validates :name, :presence =>true
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  has_many :sub_tasks

  validates :name, :length => {maximum: 50},
            :presence => true
  validates_uniqueness_of :name, :scope => :user_id
  validates_presence_of :public
  validates_inclusion_of :public, in: ["public", "private"]
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :tasks, dependent: :destroy
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?
  before_save { self.email = email.downcase }
  validates :email,    :presence =>true, :uniqueness=>true
  validates :email,    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :name,     :presence =>true, :uniqueness=>true
  validates :role,     :presence =>true
  validates :password, :presence =>true, :length => { :minimum => 8, :maximum => 40 }, :confirmation => true


  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html, :js

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/sub_tasks_controller.rb
class SubTasksController < ApplicationController
  before_action :set_sub_task, only: [:show, :edit, :update, :destroy]

  respond_to :html, :js

  def index
    @sub_tasks = SubTask.all.where( task_id: params[ :id  ]  )
    @task = Task.find( params[ :id ] )
    respond_with(@sub_tasks)
  end

  def show
    respond_with(@sub_task)
  end

  def new
    @sub_task = SubTask.new
    @sub_task.task_id = params[:id]
    @sub_task.user_id = current_user.id
    @task = Task.find( params[:id] )
    respond_with(@sub_task)
  end

  def edit
  end

  def create
    @sub_task = SubTask.new(sub_task_params)
    @sub_task.save
    respond_with(@sub_task)
  end

  def update
    @sub_task.update(sub_task_params)
    respond_with(@sub_task)
  end

  def destroy
    @sub_task.destroy
    respond_with(@sub_task)
  end

  private
    def set_sub_task
      @sub_task = SubTask.find(params[:id])
    end

    def sub_task_params
      params.require(:sub_task).permit(:name, :task_id, :user_id)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @tasks = Task.where( "user_id = :current_user_id or public = :public", { current_user_id: current_user.id, public: "public" } ).order(:user_id, :name)
    respond_with(@tasks)
  end

  def show
    respond_with(@task)
  end

  def new
    @task = Task.new
    respond_with(@task)
  end

  def edit
  end

  def create
    @task = Task.new(task_params)
    @task.save
    respond_with(@task)
  end

  def update
    @task.update(task_params)
    respond_with(@task)
  end

  def destroy
    @task.destroy
    respond_with(@task)
  end

  private
    def set_task
      @task = Task.find(params[:id])
    end

    def task_params
      params.require(:task).permit(:name, :public).merge(user_id: current_user.id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_only, :except => :show

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless current_user.admin?
      unless @user == current_user
        redirect_to :back, :alert => "Access denied."
      end
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def admin_only
    unless current_user.admin?
      redirect_to :back, :alert => "Access denied."
    end
  end

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def is_edition_allowed?(task_user_id, current_user_id)
    (current_user_id == task_user_id)
  end
end

app/helpers/sub_tasks_helper.rb
module SubTasksHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to current_user.email, edit_user_registration_path %></li>
  <li><%= link_to 'Minhas Tarefas', tasks_path, class: 'navbar-brand' %></li>
  <li><%= link_to 'Sair', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Entrar', new_user_session_path %></li>
  <li><%= link_to 'Cadastrar', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.admin? %>
    <li><%= link_to 'Usuarios', users_path %></li>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Todoapp" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Todoapp" %>">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
    <div class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    </main>
  </body>
</html>

app/views/sub_tasks/_form.html.erb
<%= simple_form_for(@sub_task) do |f| %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.hidden_field :task_id, :value => @sub_task.task_id %>
    <%= f.hidden_field :user_id, :value => current_user.id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/sub_tasks/_index.html.erb
<% @sub_tasks.each do |sub_task| %>
  <tr class="sub-task-row-<%=sub_task.id%>">
    <td><%= sub_task.name %></td>
    <td>
      <%= link_to_if is_edition_allowed?(sub_task.user_id, current_user.id), 'Editar', edit_sub_task_path(sub_task) %>
    </td>
    <td>
      <%= link_to_if is_edition_allowed?(sub_task.user_id, current_user.id), "Excluir", sub_task, method: :delete, data: { confirm: 'Tem certeza?' }, remote: true %>
    </td>
  </tr>
<% end %>

app/views/sub_tasks/destroy.js.erb
$('.sub-task-row-<%=@sub_task.id%>').bind('ajax:success', function() {
        $(this).remove();
});

app/views/sub_tasks/edit.html.erb
<div class="authform">
  <h1>Editando Sub Tarefa</h1>
  <%= render 'form' %>
  <%= link_to 'Volta', sub_tasks_path( id: @sub_task.task.id ) %>
</div>

app/views/sub_tasks/index.html.erb
<div class="row">
  <div class="span10 offset1">

    <h1>Sub Tarefas</h1>
    <h3><%= @task.name %> (<%= @task.user.name %>)</h3>

    <table class="table table-striped table-bordered table-condensed">
      <thead>
        <tr>
          <th>Descrição da Sub Tarefa</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody class="sub-task-index">
        <%= render "index" %>
      </tbody>
    </table>
    <br>

    <%= link_to_if is_edition_allowed?(@task.user_id, current_user.id), 'Nova Sub Tarefa', new_sub_task_path( id: @task.id ) %>
  </div>
</div>

app/views/sub_tasks/new.html.erb
<div class="authform">
  <h1>Nova Sub Tarefa</h1>
  <%= render 'form' %>
  <%= link_to 'Volta', sub_tasks_path( id: params[:id] || @sub_task.task_id ) %>
</div>

app/views/sub_tasks/show.html.erb
<div class="authform">
  <p>
    <strong>Descrição da Sub Tarefa:</strong>
    <%= @sub_task.name %>
  </p>
  <%= link_to 'Editar', edit_sub_task_path(@sub_task) %> |
  <%= link_to 'Volta', sub_tasks_path( id: @sub_task.task_id ) %>
</div>

app/views/tasks/_form.html.erb
<div class="authform">
  <%= simple_form_for(@task) do |f| %>

    <div class="form-inputs">
      <%= f.input :name %>
      <%= f.input :public, :label => "Publico/Privado", :collection => ['public','private'], :selected => "public" %>
    </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  <% end %>
</div>

app/views/tasks/edit.html.erb
<div class="authform">
  <h3>Editando Tarefa</h3>
  <%= render 'form' %>
  <%= link_to 'Mostrar', @task %> |
  <%= link_to 'Voltar', tasks_path %>
</div>

app/views/tasks/index.html.erb
<div class="row">
  <div class="span10 offset1">
    <h1>Tarefas</h1>
    <table class="table table-striped table-bordered table-condensed">
      <thead>
        <tr>
          <th>Descricao</th>
          <th>Publica?</th>
          <th>Dono</th>
          <th>Sub Tarefas</th>
          <th colspan="2"></th>
        </tr>
      </thead>

      <tbody>
        <% @tasks.each do |task| %>
          <tr>
            <td><strong><%= link_to_if is_edition_allowed?(task.user_id, current_user.id), task.name, edit_task_path(task) %></strong></td>
            <td><%= task.public %></td>
            <td><%= task.user.name unless task.user.blank? %></td>
            <td><%= link_to "#{task.sub_tasks.count} Itens", sub_tasks_path( id: task.id ) %></td>
            <td><%= link_to 'Mostrar', task %></td>
            <td>
              <%= link_to_if is_edition_allowed?(task.user_id, current_user.id), 'Excluir', task, method: :delete, data: { confirm: 'Tem certeza?' } %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'Nova Tarefa', new_task_path %>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="authform">
  <h3>Nova Tarefa</h3>
  <%= render 'form' %>
  <%= link_to 'Volta', tasks_path %>
</div>

app/views/tasks/show.html.erb
<div class="authform">
  <h3>Tarefa</h3>
  <p>
    <strong>Descricao:</strong>
    <%= @task.name %>
  </p>
  <p>
    <strong>Publica?:</strong>
    <%= @task.public %>
  </p>
  <p>
    <strong>User:</strong>
    <%= @task.user.name unless @task.user.blank? %>
  </p>
  <%= link_to_if is_edition_allowed?(@task.user_id, current_user.id), 'Editar', edit_task_path(@task) %> |
  <%= link_to 'Voltar', tasks_path %>
</div>

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Mudar o tipo', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Deletar usuario", user_path(user), :data => { :confirm => "Tem certeza?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>Usuario</h3>
<p>Nome: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<h3 id="app_name_effect">TodoApp - Agendamento de Tarefas</h3>
<p> <%= User.count %> <%= link_to 'usuarios', users_path %> registrados</p>